### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by pstaabp** [cubranic/Statistics-R-IO#56]
I'm trying to install this package to use in webwork.  When installing, the tests are run and it fails.  Here is the top few lines of the tests:
```
t/io-oo-rdata.t ................ Argument to Statistics::R::REXP::Integer->new() could not be dereferenced as a hash at t/io-oo-rdata.t line 72.
# Looks like your test exited with 255 before it could output anything.
t/io-oo-rdata.t ................ Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 11/11 subtests 
t/io-oo-rds.t .................. Argument to Statistics::R::REXP::Character->new() could not be dereferenced as a hash at t/lib/TestCases.pm line 204.
BEGIN failed--compilation aborted at t/lib/TestCases.pm line 204.
Compilation failed in require at t/io-oo-rds.t line 14.
BEGIN failed--compilation aborted at t/io-oo-rds.t line 14.
# Looks like your test exited with 255 before it could output anything.
t/io-oo-rds.t .................. Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 66/66 subtests 
t/io-oo-rserve-eval-live.t ..... Argument to Statistics::R::REXP::Character->new() could not be dereferenced as a hash at t/lib/TestCases.pm line 204.
BEGIN failed--compilation aborted at t/lib/TestCases.pm line 204.
Compilation failed in require at t/io-oo-rserve-eval-live.t line 41.
BEGIN failed--compilation aborted at t/io-oo-rserve-eval-live.t line 41.
t/io-oo-rserve-eval-live.t ..... Dubious, test returned 255 (wstat 65280, 0xff00)
```

I'm trying to get this running on MacOS currently and have rserve running and have tested it from another r client.

**Comment by cubranic** [comment]
With which Perl version do you see this?

**Comment by pstaabp** [comment]
I'm running 5.18

**Comment by cubranic** [comment]
I don't understand why, it works on my Mac, with Perl 5.18:
```
[Statistics-R-IO] $ prove -l
t/io-oo-rdata.t ................ ok
t/io-oo-rds.t .................. ok
t/io-oo-rserve-eval-live.t ..... skipped: Cannot connect to Rserve server at localhost:6311
t/io-oo-rserve-eval-mock.t ..... ok
t/io-oo-rserve-getfile-live.t .. skipped: Cannot connect to Rserve server at localhost:6311
t/io-oo-rserve-sereval-live.t .. skipped: Cannot connect to Rserve server at localhost:6311
t/io-oo-rserve-sereval-mock.t .. ok
t/io-parser.t .................. ok
t/io-parserstate.t ............. ok
t/io-qap.t ..................... ok
t/io-rdata.t ................... ok
t/io-rds.t ..................... ok
t/io-rserve-eval.t ............. skipped: Cannot connect to Rserve server at localhost:6311
t/io-rserve.t .................. ok
t/io-unserialize.t ............. ok
t/rexp-baseenvironment.t ....... ok
t/rexp-character.t ............. ok
t/rexp-closure.t ............... ok
t/rexp-complex.t ............... ok
t/rexp-double.t ................ ok
t/rexp-emptyenvironment.t ...... ok
t/rexp-environment.t ........... ok
t/rexp-expression.t ............ ok
t/rexp-globalenvironment.t ..... ok
t/rexp-integer.t ............... ok
t/rexp-language.t .............. ok
t/rexp-list.t .................. ok
t/rexp-logical.t ............... ok
t/rexp-null.t .................. ok
t/rexp-raw.t ................... ok
t/rexp-s3.t .................... ok
t/rexp-s4.t .................... ok
t/rexp-symbol.t ................ ok
t/rexp-unknown.t ............... ok
t/rexp-vector.t ................ ok
t/rexp.t ....................... ok
All tests successful.
Files=36, Tests=860, 10 wallclock secs ( 0.56 usr  0.14 sys +  9.81 cusr  0.43 csys = 10.94 CPU)
Result: PASS
```

**Comment by cubranic** [comment]
Can you provide a bit more information about how you're running the tests? 

It's also possible that there is some difference in package versions that we have installed, or something like that. That line where the `t/io-oo-rdata.t` is failing for you is completely innocuous.

My `Class::Tiny` is 1.006, while `Class::Tiny::Antlers` is 0.023. (These are their latest released versions, since I just installed all deps into a fresh `plenv`.)

**Comment by cubranic** [comment]
In particular, tests pass for me both on the Github source (`prove -l`), and on the 1.0001 .tar.gz downloaded from MetaCPAN (`tar xzf ...; cd Statistics-R-IO-1.0001; perl Makefile.PL; make test`).

**Comment by pstaabp** [comment]
It appears it was the `Class::Tiny` module.  The version I had installed was 1.014 and `cpan-outdated` did not pick up on this being old.   A force reinstall of  `Class::Tiny` did the trick.  Aren't there ways of checking to make sure the dependent modules are up to date?

**Comment by cubranic** [comment]
Do you mean "0.014"? Because "1.014" has not yet been released, we're only at "1.006".

I hadn't specified the minimum version for Class::Tiny because I didn't want to set it lower than necessary. I'll do so and release a bugfix version with this set to the known working version of Class::Tiny.

**Comment by pstaabp** [comment]
On my Mac (running 10.12.5), using the built-in perl, the version that was installed is in `/System/Library/Perl/Extras/5.18/Class/Tiny.pm`, the top of the file is:

```
use 5.008001;
use strict;
no strict 'refs';
use warnings;

package Class::Tiny;
# ABSTRACT: Minimalist class construction
our $VERSION = '0.014'; # VERSION

use Carp ();

# load as .pm to hide from min version scanners
require( $] >= 5.010 ? "mro.pm" : "MRO/Compat.pm" ); ## no critic:

my %CLASS_ATTRIBUTES;

sub import {
    my $class = shift;
    my $pkg   = caller;
    $class->prepare_class($pkg);
    $class->create_attributes( $pkg, @_ ) if @_;
}
```

I installed the current version (1.006) using `cpanm`, which installed in `/Library/Perl/5.18/Class/Tiny.pm` and that seems to be working.    I was puzzled why I had an existing version that was not the latest, but with a larger version number.

**Comment by cubranic** [comment]
Fixed in 2c7012250a18bc5192bd0531adb2636285ca6440 and released as Statistics::R::IO v1.0002.
